class typeUnits {
  static List<String> lengthX = [
    "meters",
    "centimeters",
    "inches",
    "feet",
    "nautical miles",
    "yards",
    "miles",
    "millimeters",
    "micrometers",
    "nanometers",
    "angstroms",
    "picometers",
    "kilometers",
    "astronomical units",
    "light years",
    "parsec",
    "mils",
  ];
  static List<String> digitalDataX = [
    "bit",
    "nibble",
    "kilobit",
    "megabit",
    "gigabit",
    "terabit",
    "petabit",
    "exabit",
    "kibibit",
    "mebibit",
    "gibibit",
    "tebibit",
    "pebibit",
    "exbibit",
    "byte",
    "kilobyte",
    "megabyte",
    "gigabyte",
    "terabyte",
    "petabyte",
    "exabyte",
    "kibibyte",
    "mebibyte",
    "gibibyte",
    "tebibyte",
    "pebibyte",
    "exbibyte",
  ];
  static List<String> angleX = [
    "degree",
    "minutes",
    "seconds",
    "radians",
  ];
  static List<String> areaX = [
    "square meters",
    "square centimeters",
    "square inches",
    "square feet",
    "square miles",
    "square yard",
    "square millimeters",
    "square kilometers",
    "hectares",
    "acres",
    "are",
  ];
  static List<String> tempX = [
    "fahrenheit",
    "celsius",
    "kelvin",
    "reamur",
    "romer",
    "delisle",
    "rankine",
  ];
  static List<String> energyX = [
    "joules",
    "calories",
    "kilowatt hours",
    "electronvolts",
  ];
  static List<String> volumeX = [
    "cubic meters",
    "liters",
    "imperial gallons",
    "us gallons",
    "imperial pints",
    "us  pints",
    "milliliters",
    "tablespoons us",
    "australian tablespoons",
    "cups",
    "cubic centimeters",
    "cubic feet",
    "cubic inches",
    "cubic millimeters",
    "imperial fluid ounces",
    "us fluid ounces",
    "imperial gill",
    "us gill",
  ];
  static List<String> forceX = [
    "newton",
    "dyne",
    "pound force",
    "kilogram force",
    "poundal",
  ];
  static List<String> massX = [
    "grams",
    "ettograms",
    "kilograms",
    "pounds",
    "ounces",
    "quintals",
    "tons",
    'milligrams',
    "uma", //unified atomic mass unit
    "carats",
    "centigrams",
    "pennyweights",
    "troy ounces",
    "stones",
  ];
  static List<String> powerX = [
    "watt",
    "milliwatt",
    "kilowatt",
    "megawatt",
    "gigawatt",
    "european horse power",
    'imperial horse power',
  ];

  static List<String> pressureX = [
    "pascal",
    "atmosphere",
    "bar",
    "millibar",
    "psi",
    'torr',
  ];
  static List<String> shoeSizeX = [
    "centimeters",
    "inches",
    "eu china",
    "uk india child",
    'uk india man',
    "uk india woman",
    'usa canada child',
    "usa canada man",
    "usa canada woman",
    "japan",
  ];
  static List<String> siPrefixeX = [
    "base",
    "deca",
    "hecto",
    "kilo",
    "mega",
    "giga",
    "tera",
    "peta",
    "exa",
    "zetta",
    "yotta",
    "deci",
    "centi",
    "milli",
    "micro",
    "nano",
    "pico",
    "femto",
    "atto",
    "zepto",
    "yocto",
  ];
  static List<String> speedX = [
    "meters per second",
    "kilometers per hour",
    "miles per hour",
    "knots",
    "feets per second",
  ];
  static List<String> timeX = [
    "seconds",
    "deciseconds",
    "centiseconds",
    "milliseconds",
    "microseconds",
    "nanoseconds",
    "minutes",
    "hours",
    "days",
    "weeks",
    "years 365",
    "lustrum",
    "decades",
    "centuries",
    "millennium",
  ];
  static List<String> torqueX = [
    "newton meter",
    "dyne meter",
    "pound force feet",
    "kilogram force meter",
    "poundal meter",
  ];
}
